// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_RootPanel);
    lv_obj_set_width(ui_RootPanel, lv_pct(100));
    lv_obj_set_height(ui_RootPanel, lv_pct(100));
    lv_obj_set_align(ui_RootPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top_Panel_Speed = lv_obj_create(ui_RootPanel);
    lv_obj_remove_style_all(ui_Top_Panel_Speed);
    lv_obj_set_height(ui_Top_Panel_Speed, 50);
    lv_obj_set_width(ui_Top_Panel_Speed, lv_pct(80));
    lv_obj_set_x(ui_Top_Panel_Speed, 0);
    lv_obj_set_y(ui_Top_Panel_Speed, -10);
    lv_obj_set_align(ui_Top_Panel_Speed, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Top_Panel_Speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Top_Panel_Speed, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Top_Panel_Speed, lv_color_hex(0x252424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Top_Panel_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Top_Panel_Speed, lv_color_hex(0x787676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Top_Panel_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Top_Panel_Speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Top_Panel_Speed, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Top_Panel_Speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Top_Panel_Speed, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Top_Panel_Speed, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Top_Panel_Speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Top_Panel_Speed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleSpeed = lv_label_create(ui_Top_Panel_Speed);
    lv_obj_set_width(ui_TitleSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TitleSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleSpeed, "Speedometer");
    lv_obj_set_style_text_color(ui_TitleSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleSpeed, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Top_Panel_Speed);
    lv_obj_set_width(ui_Button1, lv_pct(100));
    lv_obj_set_height(ui_Button1, lv_pct(100));
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speedpanel = lv_obj_create(ui_RootPanel);
    lv_obj_remove_style_all(ui_Speedpanel);
    lv_obj_set_height(ui_Speedpanel, 140);
    lv_obj_set_width(ui_Speedpanel, lv_pct(100));
    lv_obj_set_x(ui_Speedpanel, 0);
    lv_obj_set_y(ui_Speedpanel, -120);
    lv_obj_set_align(ui_Speedpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedpanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Speedpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Speedpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Speedpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBJ = lv_img_create(ui_Speedpanel);
    lv_img_set_src(ui_SpeedBJ, &ui_img_speedbg_png);
    lv_obj_set_width(ui_SpeedBJ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedBJ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedBJ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedBJ, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeedBJ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_SpeedBJ);
    lv_slider_set_range(ui_Slider1, 0, 200);
    lv_slider_set_value(ui_Slider1, 120, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 320);
    lv_obj_set_height(ui_Slider1, 140);
    lv_obj_set_x(ui_Slider1, 1);
    lv_obj_set_y(ui_Slider1, 0);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_speedfg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MinSpeedLab = lv_label_create(ui_Speedpanel);
    lv_obj_set_width(ui_MinSpeedLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinSpeedLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinSpeedLab, 15);
    lv_obj_set_y(ui_MinSpeedLab, 0);
    lv_obj_set_align(ui_MinSpeedLab, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_MinSpeedLab, "0");
    lv_obj_set_style_text_color(ui_MinSpeedLab, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinSpeedLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinSpeedLab, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxSpeedLab = lv_label_create(ui_Speedpanel);
    lv_obj_set_width(ui_MaxSpeedLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxSpeedLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxSpeedLab, -10);
    lv_obj_set_y(ui_MaxSpeedLab, -5);
    lv_obj_set_align(ui_MaxSpeedLab, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_MaxSpeedLab, "200");
    lv_obj_set_style_text_color(ui_MaxSpeedLab, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxSpeedLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MaxSpeedLab, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassPanel = lv_obj_create(ui_RootPanel);
    lv_obj_remove_style_all(ui_CompassPanel);
    lv_obj_set_width(ui_CompassPanel, lv_pct(100));
    lv_obj_set_height(ui_CompassPanel, lv_pct(60));
    lv_obj_set_x(ui_CompassPanel, 0);
    lv_obj_set_y(ui_CompassPanel, 5);
    lv_obj_set_align(ui_CompassPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_CompassPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassImg = lv_img_create(ui_CompassPanel);
    lv_img_set_src(ui_CompassImg, &ui_img_compass_png);
    lv_obj_set_width(ui_CompassImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CompassImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CompassImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CompassImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CompassLabel = lv_label_create(ui_CompassImg);
    lv_obj_set_width(ui_CompassLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompassLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompassLabel, 0);
    lv_obj_set_y(ui_CompassLabel, -5);
    lv_obj_set_align(ui_CompassLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassLabel, "360");
    lv_obj_set_style_text_color(ui_CompassLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompassLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CompassLabel, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DspSpeedPanel = lv_obj_create(ui_RootPanel);
    lv_obj_remove_style_all(ui_DspSpeedPanel);
    lv_obj_set_height(ui_DspSpeedPanel, 80);
    lv_obj_set_width(ui_DspSpeedPanel, lv_pct(100));
    lv_obj_set_x(ui_DspSpeedPanel, 0);
    lv_obj_set_y(ui_DspSpeedPanel, -50);
    lv_obj_set_align(ui_DspSpeedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DspSpeedPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DspSpeedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DspSpeedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedUnitLab = lv_label_create(ui_DspSpeedPanel);
    lv_obj_set_width(ui_SpeedUnitLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedUnitLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedUnitLab, -10);
    lv_obj_set_y(ui_SpeedUnitLab, 10);
    lv_obj_set_align(ui_SpeedUnitLab, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_SpeedUnitLab, "kmh");
    lv_obj_set_style_text_font(ui_SpeedUnitLab, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBackGround = lv_label_create(ui_DspSpeedPanel);
    lv_obj_set_width(ui_SpeedBackGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedBackGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedBackGround, -55);
    lv_obj_set_y(ui_SpeedBackGround, -15);
    lv_obj_set_align(ui_SpeedBackGround, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_SpeedBackGround, "000");
    lv_obj_set_style_text_color(ui_SpeedBackGround, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedBackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedBackGround, &ui_font_Display90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_DspSpeedPanel);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, -55);
    lv_obj_set_y(ui_SpeedLabel, -15);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_SpeedLabel, "120");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &ui_font_Display90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPSWaiting = lv_spinner_create(ui_RootPanel, 1000, 90);
    lv_obj_set_width(ui_GPSWaiting, 20);
    lv_obj_set_height(ui_GPSWaiting, 20);
    lv_obj_set_x(ui_GPSWaiting, -5);
    lv_obj_set_y(ui_GPSWaiting, 5);
    lv_obj_set_align(ui_GPSWaiting, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_GPSWaiting, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_GPSWaiting, lv_color_hex(0x576057), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPSWaiting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GPSWaiting, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GPSWaiting, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPSWaiting, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GPSWaiting, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PoweredBySpeed = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_PoweredBySpeed);
    lv_obj_set_height(ui_PoweredBySpeed, 30);
    lv_obj_set_width(ui_PoweredBySpeed, lv_pct(100));
    lv_obj_set_align(ui_PoweredBySpeed, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PoweredBySpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EESRSpeedLab = lv_label_create(ui_PoweredBySpeed);
    lv_obj_set_width(ui_EESRSpeedLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EESRSpeedLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EESRSpeedLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EESRSpeedLab, "www.modulemore.com");
    lv_obj_set_style_text_color(ui_EESRSpeedLab, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EESRSpeedLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_EESRSpeedLab, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EESRSpeedLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
