// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RootPanelGPS = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_RootPanelGPS);
    lv_obj_set_width(ui_RootPanelGPS, lv_pct(100));
    lv_obj_set_height(ui_RootPanelGPS, lv_pct(100));
    lv_obj_set_align(ui_RootPanelGPS, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanelGPS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanelGPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top_PanelGPS = lv_obj_create(ui_RootPanelGPS);
    lv_obj_remove_style_all(ui_Top_PanelGPS);
    lv_obj_set_height(ui_Top_PanelGPS, 50);
    lv_obj_set_width(ui_Top_PanelGPS, lv_pct(80));
    lv_obj_set_x(ui_Top_PanelGPS, 0);
    lv_obj_set_y(ui_Top_PanelGPS, -10);
    lv_obj_set_align(ui_Top_PanelGPS, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Top_PanelGPS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Top_PanelGPS, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Top_PanelGPS, lv_color_hex(0x252424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Top_PanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Top_PanelGPS, lv_color_hex(0x787676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Top_PanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Top_PanelGPS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Top_PanelGPS, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Top_PanelGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Top_PanelGPS, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Top_PanelGPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Top_PanelGPS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Top_PanelGPS, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleGPS = lv_label_create(ui_Top_PanelGPS);
    lv_obj_set_width(ui_TitleGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TitleGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleGPS, "GPS Information");
    lv_obj_set_style_text_color(ui_TitleGPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleGPS, &ui_font_Display24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Top_PanelGPS);
    lv_obj_set_width(ui_Button3, lv_pct(100));
    lv_obj_set_height(ui_Button3, lv_pct(100));
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BodyPanel = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_BodyPanel);
    lv_obj_set_height(ui_BodyPanel, 420);
    lv_obj_set_width(ui_BodyPanel, lv_pct(100));
    lv_obj_set_align(ui_BodyPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_BodyPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BodyPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BodyPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Satellite_panel = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_Satellite_panel);
    lv_obj_set_width(ui_Satellite_panel, 120);
    lv_obj_set_height(ui_Satellite_panel, 80);
    lv_obj_set_x(ui_Satellite_panel, 10);
    lv_obj_set_y(ui_Satellite_panel, 0);
    lv_obj_clear_flag(ui_Satellite_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Satellite_panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Satellite_panel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Satellite_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Satellite_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SatelliteTitle = lv_label_create(ui_Satellite_panel);
    lv_obj_set_width(ui_SatelliteTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SatelliteTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SatelliteTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SatelliteTitle, "Satellites");
    lv_obj_set_style_text_font(ui_SatelliteTitle, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Satellites = lv_label_create(ui_Satellite_panel);
    lv_obj_set_width(ui_Satellites, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Satellites, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Satellites, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Satellites, "4");
    lv_obj_set_style_text_color(ui_Satellites, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Satellites, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Satellites, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Degree_panel = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_Degree_panel);
    lv_obj_set_width(ui_Degree_panel, 120);
    lv_obj_set_height(ui_Degree_panel, 80);
    lv_obj_set_x(ui_Degree_panel, -10);
    lv_obj_set_y(ui_Degree_panel, 0);
    lv_obj_set_align(ui_Degree_panel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Degree_panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Degree_panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Degree_panel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Degree_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Degree_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DegreeTitle = lv_label_create(ui_Degree_panel);
    lv_obj_set_width(ui_DegreeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DegreeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DegreeTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_DegreeTitle, "Degree");
    lv_obj_set_style_text_font(ui_DegreeTitle, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Degree = lv_label_create(ui_Degree_panel);
    lv_obj_set_width(ui_Degree, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Degree, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Degree, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Degree, "120");
    lv_obj_set_style_text_color(ui_Degree, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Degree, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Degree, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Coordonate_Panel = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_Coordonate_Panel);
    lv_obj_set_width(ui_Coordonate_Panel, 300);
    lv_obj_set_height(ui_Coordonate_Panel, 120);
    lv_obj_set_x(ui_Coordonate_Panel, 10);
    lv_obj_set_y(ui_Coordonate_Panel, 94);
    lv_obj_clear_flag(ui_Coordonate_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Coordonate_Panel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Coordonate_Panel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Coordonate_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Coordonate_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordinteTitle = lv_label_create(ui_Coordonate_Panel);
    lv_obj_set_width(ui_CoordinteTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoordinteTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CoordinteTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CoordinteTitle, "Coordinates");
    lv_obj_set_style_text_font(ui_CoordinteTitle, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordonateTxt = lv_label_create(ui_Coordonate_Panel);
    lv_obj_set_width(ui_CoordonateTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoordonateTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoordonateTxt, 10);
    lv_obj_set_y(ui_CoordonateTxt, 0);
    lv_obj_set_align(ui_CoordonateTxt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CoordonateTxt, "Lat:\nLgn:");
    lv_obj_set_style_text_color(ui_CoordonateTxt, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CoordonateTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CoordonateTxt, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoordonateVal = lv_label_create(ui_Coordonate_Panel);
    lv_obj_set_width(ui_CoordonateVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoordonateVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoordonateVal, 80);
    lv_obj_set_y(ui_CoordonateVal, 0);
    lv_obj_set_align(ui_CoordonateVal, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CoordonateVal, "40.120.58\n-125.05.64");
    lv_obj_set_style_text_color(ui_CoordonateVal, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CoordonateVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CoordonateVal, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedGpsPanel = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_SpeedGpsPanel);
    lv_obj_set_width(ui_SpeedGpsPanel, 300);
    lv_obj_set_height(ui_SpeedGpsPanel, 80);
    lv_obj_set_x(ui_SpeedGpsPanel, 0);
    lv_obj_set_y(ui_SpeedGpsPanel, -120);
    lv_obj_set_align(ui_SpeedGpsPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_SpeedGpsPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SpeedGpsPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedGpsPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedGpsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeedGpsPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedGPSText = lv_label_create(ui_SpeedGpsPanel);
    lv_obj_set_width(ui_SpeedGPSText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedGPSText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedGPSText, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SpeedGPSText, "Speed (km/h)");
    lv_obj_set_style_text_font(ui_SpeedGPSText, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedGPSVal = lv_label_create(ui_SpeedGpsPanel);
    lv_obj_set_width(ui_SpeedGPSVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedGPSVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedGPSVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedGPSVal, "120");
    lv_obj_set_style_text_color(ui_SpeedGPSVal, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedGPSVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedGPSVal, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeGpsPanel = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_AltitudeGpsPanel);
    lv_obj_set_width(ui_AltitudeGpsPanel, 300);
    lv_obj_set_height(ui_AltitudeGpsPanel, 80);
    lv_obj_set_x(ui_AltitudeGpsPanel, 0);
    lv_obj_set_y(ui_AltitudeGpsPanel, -33);
    lv_obj_set_align(ui_AltitudeGpsPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_AltitudeGpsPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AltitudeGpsPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AltitudeGpsPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AltitudeGpsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AltitudeGpsPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeTitle = lv_label_create(ui_AltitudeGpsPanel);
    lv_obj_set_width(ui_AltitudeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AltitudeTitle, "Altitude (meters)");
    lv_obj_set_style_text_font(ui_AltitudeTitle, &ui_font_Display16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AltitudeVal = lv_label_create(ui_AltitudeGpsPanel);
    lv_obj_set_width(ui_AltitudeVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AltitudeVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AltitudeVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AltitudeVal, "120");
    lv_obj_set_style_text_color(ui_AltitudeVal, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AltitudeVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AltitudeVal, &ui_font_Display40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweredByGPS = lv_obj_create(ui_BodyPanel);
    lv_obj_remove_style_all(ui_PoweredByGPS);
    lv_obj_set_height(ui_PoweredByGPS, 30);
    lv_obj_set_width(ui_PoweredByGPS, lv_pct(100));
    lv_obj_set_align(ui_PoweredByGPS, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PoweredByGPS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EESRGPSLab = lv_label_create(ui_PoweredByGPS);
    lv_obj_set_width(ui_EESRGPSLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EESRGPSLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EESRGPSLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EESRGPSLab, "www.modulemore.com");
    lv_obj_set_style_text_color(ui_EESRGPSLab, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EESRGPSLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_EESRGPSLab, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EESRGPSLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
