// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_RootPanel;
lv_obj_t * ui_Top_Panel_Speed;
lv_obj_t * ui_TitleSpeed;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Speedpanel;
lv_obj_t * ui_SpeedBJ;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_MinSpeedLab;
lv_obj_t * ui_MaxSpeedLab;
lv_obj_t * ui_CompassPanel;
lv_obj_t * ui_CompassImg;
lv_obj_t * ui_CompassLabel;
lv_obj_t * ui_DspSpeedPanel;
lv_obj_t * ui_SpeedUnitLab;
lv_obj_t * ui_SpeedBackGround;
lv_obj_t * ui_SpeedLabel;
lv_obj_t * ui_GPSWaiting;
lv_obj_t * ui_PoweredBySpeed;
lv_obj_t * ui_EESRSpeedLab;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_RootPanelGPS;
lv_obj_t * ui_Top_PanelGPS;
lv_obj_t * ui_TitleGPS;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_BodyPanel;
lv_obj_t * ui_Satellite_panel;
lv_obj_t * ui_SatelliteTitle;
lv_obj_t * ui_Satellites;
lv_obj_t * ui_Degree_panel;
lv_obj_t * ui_DegreeTitle;
lv_obj_t * ui_Degree;
lv_obj_t * ui_Coordonate_Panel;
lv_obj_t * ui_CoordinteTitle;
lv_obj_t * ui_CoordonateTxt;
lv_obj_t * ui_CoordonateVal;
lv_obj_t * ui_SpeedGpsPanel;
lv_obj_t * ui_SpeedGPSText;
lv_obj_t * ui_SpeedGPSVal;
lv_obj_t * ui_AltitudeGpsPanel;
lv_obj_t * ui_AltitudeTitle;
lv_obj_t * ui_AltitudeVal;
lv_obj_t * ui_PoweredByGPS;
lv_obj_t * ui_EESRGPSLab;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
