// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Speedometer

#ifndef _SPEEDOMETER_UI_H
#define _SPEEDOMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RootPanel;
extern lv_obj_t * ui_Top_Panel_Speed;
extern lv_obj_t * ui_TitleSpeed;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Speedpanel;
extern lv_obj_t * ui_SpeedBJ;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_MinSpeedLab;
extern lv_obj_t * ui_MaxSpeedLab;
extern lv_obj_t * ui_CompassPanel;
extern lv_obj_t * ui_CompassImg;
extern lv_obj_t * ui_CompassLabel;
extern lv_obj_t * ui_DspSpeedPanel;
extern lv_obj_t * ui_SpeedUnitLab;
extern lv_obj_t * ui_SpeedBackGround;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_GPSWaiting;
extern lv_obj_t * ui_PoweredBySpeed;
extern lv_obj_t * ui_EESRSpeedLab;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_RootPanelGPS;
extern lv_obj_t * ui_Top_PanelGPS;
extern lv_obj_t * ui_TitleGPS;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_BodyPanel;
extern lv_obj_t * ui_Satellite_panel;
extern lv_obj_t * ui_SatelliteTitle;
extern lv_obj_t * ui_Satellites;
extern lv_obj_t * ui_Degree_panel;
extern lv_obj_t * ui_DegreeTitle;
extern lv_obj_t * ui_Degree;
extern lv_obj_t * ui_Coordonate_Panel;
extern lv_obj_t * ui_CoordinteTitle;
extern lv_obj_t * ui_CoordonateTxt;
extern lv_obj_t * ui_CoordonateVal;
extern lv_obj_t * ui_SpeedGpsPanel;
extern lv_obj_t * ui_SpeedGPSText;
extern lv_obj_t * ui_SpeedGPSVal;
extern lv_obj_t * ui_AltitudeGpsPanel;
extern lv_obj_t * ui_AltitudeTitle;
extern lv_obj_t * ui_AltitudeVal;
extern lv_obj_t * ui_PoweredByGPS;
extern lv_obj_t * ui_EESRGPSLab;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_speedbg_png);    // assets/speedBG.png
LV_IMG_DECLARE(ui_img_speedfg_png);    // assets/speedFG.png
LV_IMG_DECLARE(ui_img_compass_png);    // assets/compass.png



LV_FONT_DECLARE(ui_font_Display16);
LV_FONT_DECLARE(ui_font_Display24);
LV_FONT_DECLARE(ui_font_Display40);
LV_FONT_DECLARE(ui_font_Display90);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
